=== MacBootglass/insa/TechnoWeb/TP2/src/dtd/cd.dtd
<?xml version="1.0" encoding="UTFâˆ’8"?>
  <!ELEMENT cd (interprete+, titre, groupe?, edition, admin, critiques*)>
    <!ELEMENT interprete (nom, prenom)>
      <!ELEMENT nom (#PCDATA)>
      <!ELEMENT prenom (#PCDATA)>
  <!ELEMENT titre (#PCDATA)>
  <!ELEMENT groupe (#PCDATA)>
  <!ELEMENT edition (nom, lieu, pays, annee)>
    <!ELEMENT lieu (#PCDATA)>
    <!ELEMENT pays (#PCDATA)>
    <!ELEMENT annee (#PCDATA)>
  <!ELEMENT admin (plages, isbn*, prix)>
    <!ELEMENT plages (#PCDATA)>
    <!ELEMENT isbn (#PCDATA)>
      <!ATTLIST isbn type CDATA #REQUIRED>
    <!ELEMENT prix (#PCDATA)>
      <!ATTLIST prix monnaie CDATA #REQUIRED>
  <!ELEMENT critiques (resume, remarque)>
    <!ELEMENT resume (para+)>
      <!ELEMENT para (#PCDATA)>
    <!ELEMENT remarque (#PCDATA)>

=== MacBootglass/insa/TechnoWeb/TP2/src/cdB.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE cd SYSTEM "dtd/cd.dtd">

<cd>
  <interprete>
    <nom>Guillot</nom>
    <prenom>Agnès</prenom>
  </interprete>

  <interprete>
    <nom>Daucé</nom>
    <prenom>Emmanuel</prenom>
  </interprete>

  <titre>Rock en stock !</titre>

  <groupe>Au fond de l'eau</groupe>

  <edition>
    <nom>SoundSystem</nom>
    <lieu>Paris</lieu>
    <pays>France</pays>
    <annee>2002</annee>
  </edition>

  <admin>
    <plages>316</plages>
    <prix monnaie="EUR">80.00</prix>
  </admin>

  <critiques>
    <resume>
      <para>Blabla.</para>
    </resume>
    <remarque>Voir aussi le site Hermès: http://www.soundsystem.fr/fr/.</remarque>
  </critiques>
</cd>
